name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python Env
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install Python Dependencies
      run: pip install -r requirements.txt

    - name: Install
      run: python -m pip install -e .
    
    - name: Test
      run: python -m pytest $GITHUB_WORKSPACE/test/